### ISSUE TITLE
Crashing after CS GO UPDATE 02/02/2023 - SigScan Failed

### ISSUE THREAD

**Issue by hobsRKM** [Nixer1337/AwesomeHvH#7]
If i load this extension it crashes, was fine till the update of csgo of feb on linux. Added the latest signature.txt file from this repository to gamedata, still server doesn't boot. Server boots only after removing this extension

Please fix this extension is awsome.

 [AwesomeHvH] Sigscan for RecordDataIntoTrack failed
L 02/04/2023 - 06:02:53: [SM] Unable to load extension "AwesomeHvH.ext.2.csgo.ext": Hooking RecordDataIntoTrack failed
L 02/04/2023 - 06:02:53: [SDKTOOLS] Sigscan for FireOutput failed
L 02/04/2023 - 06:02:53: [SDKTOOLS] Sigscan for WriteBaselines failed
L 02/04/2023 - 06:02:53: [SDKTOOLS] Failed to find WriteBaselines signature -- stringtable error workaround disabled.

**Comment by Nixer1337** [comment]
download latest awesomehvh version
https://www.unknowncheats.me/forum/downloads.php?do=file&id=38456

update sourcemod, then update gamedata for this extension:
https://github.com/Nixer1337/AwesomeHvH/blob/main/awesome_hvh.games.txt

**Comment by hobsRKM** [comment]
I have latest source mode and downloaded latest AWSOME extension and used the the file .txt as provided. Now server doesn't crash but extension doesn't load
 [01] SourceMod (1.11.0.6928) by AlliedModders LLC
 
 
 [SM] Unable to load extension "AwesomeHvH.ext.2.csgo.ext": /data/service1595/data/service_item_1906284/csgo/addons/sourcemod/extensions/AwesomeHvH.ext.2.csgo.ext.so: cannot open shared object file: No such file or directory

**Comment by Nixer1337** [comment]
This error message is indicating that the SourceMod extension "AwesomeHvH.ext.2.csgo.ext" could not be loaded because the .so file could not be found in the specified directory. This could be due to the file being missing or having incorrect file permissions, or the directory path being incorrect. Check the specified path and verify that the file exists and has the correct permissions, or try locating the file in a different directory.

**Comment by hobsRKM** [comment]
Thanks, my bad i was seeing someother old file.
